# Generated by Django 2.1.3 on 2018-12-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='movies/posters/2018/12/19/'),
        ),
        migrations.AlterField(
            model_name='themesong',
            name='track',
            field=models.FileField(upload_to='movies/songs/2018/12/19/'),
        ),
    ]
